[package]
name = "parsec-se-driver"
version = "0.1.0"
authors = ["Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "Parsec Secure Element driver implementation"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-se-driver"
readme = "README.md"
keywords = ["parsec"]
categories = ["development-tools"]
edition = "2018"
documentation = "https://parallaxsecond.github.io/"

# Currently this library hardcodes the provider and the authentication method choices:
#   * provider is TPM
#   * authentication is direct authentication
[lib]
name = "parsec_tpm_direct_se_driver"
crate-type = ["cdylib", "staticlib"]

[dependencies]
#parsec-client = "0.2.0"
parsec-client = { version = "0.2.0", path = "../parsec-client-rust" }
lazy_static = "1.4.0"
uuid = "0.7.4"

[build-dependencies]
curl = "0.4.28"
bindgen = "0.53.2"
