[package]
name = "parsec-se-driver"
version = "0.1.0"
authors = ["Paul Howard <paul.howard@arm.com>",
           "Ionut Mihalcea <ionut.mihalcea@arm.com>",
           "Hugues de Valon <hugues.devalon@arm.com>"]
description = "Parsec Secure Element driver implementation"
license = "Apache-2.0"
repository = "https://github.com/parallaxsecond/parsec-se-driver"
readme = "README.md"
keywords = ["parsec"]
categories = ["development-tools"]
edition = "2018"
documentation = "https://parallaxsecond.github.io/"

# Currently this library hardcodes the provider and the authentication method choices:
#   * provider is TPM
#   * authentication is direct authentication
[lib]
name = "parsec_tpm_direct_se_driver"
crate-type = ["cdylib", "staticlib"]

[dependencies]
parsec-client = "0.4.0"
lazy_static = "1.4.0"
uuid = "0.7.4"
psa-crypto = "0.1.0"
log = "0.4.8"
env_logger = { version = "0.7.1", optional = true }

# Use a revision of psa-crypto-sys that is linkable with Mbed TLS 2.22.0 until a next
# version is updated.
[patch.crates-io]
psa-crypto-sys = { git = 'https://github.com/parallaxsecond/rust-psa-crypto', rev = "b8e1d736cb8f27d275d266a0b833504cde660956" }

[build-dependencies]
curl = "0.4.28"
bindgen = "0.53.2"

[features]
default = ["logging"]
logging = ["env_logger"]
